config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    collection do
      get :portal
    end
  end
  resources :languages
  resources :sections
  resources :issues, only: [:index, :show] do
    collection do
      get :portal
    end
  end
  resources :infomations, except: [:edit] do
    collection do
      get :complete
    end
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'issues#portal'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :language, optional: true
  belongs_to :section, optional: true

  validates :language_id,
    presence: true

  validates :section_id,
    presence: true

  validates :title,
    presence: true

  validates :body,
    presence: true

  validate :new_released, on: :create

  def new_released
    if is_released
      errors[:base] << "一度、プレビューしてから公開するを選択してください"
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_language, only: [:index, :new, :edit, :create, :update]
  before_action :set_section, only: [:new, :edit, :create, :update]
  before_action :authenticate_user

    def index
    if article_params[:language_id].present?
      @articles = Article.where(language_id: article_params[:language_id])
    else
      @articles = Article.all
    end
  end

  def show
    @items = web_scraping(@article.body)
  end

  def new
    @article = Article.new
    if params[:language_id]
      @article.attributes = { language_id: params[:language_id] }
    end
  end

  def edit
    @sections = Section.where(language_id: @article.language_id)
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: '記事が作成されました'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: '記事が更新されました'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: '記事が削除されました'
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def set_language
      @languages = Language.all
    end

    def set_section
      if params[:language_id]
        # バリデーションによる再描画時に、セクションタイトルの値保持用の変数
        @@global_language = params[:language_id]
        @sections = Section.where(language_id: params[:language_id])
      else
        if @@global_language ||= nil
          @sections = Section.where(language_id: @@global_language)
        else
          @sections = {}
        end
      end
    end

    def article_params
      params.fetch(:article, {}).permit(:language_id, :section_id, :title, :body, :is_released)
    end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <%= render 'partial/errors', error_model: article %>
  <% end %>

  <table id="form_table">
    <tr>
      <td>
        <%= form.label :language_id %>:
      </td>
      <td>
        <%= form.collection_select :language_id, @languages, :id, :name, { include_blank: true }, class:"form-control col-md-8 ml-10", id:"language_id" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :section_id %>:
      </td>
      <td>
        <%= form.collection_select :section_id, @sections, :id, :title, { include_blank: true }, class:"form-control col-md-8 ml-10" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :title %>:
      </td>
      <td>
        <%= form.text_area :title, class:"form-control col-md-11 ml-10", rows: 5 %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :body %>:
      </td>
      <td>
        <%= form.text_area :body, class:"form-control col-md-11 ml-10", rows: 25 %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :is_released %>:
      </td>
      <td>
        <%= form.check_box :is_released, class:"form-control" %>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>記事を編集</h1>
<hr>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="">
  <h1>記事一覧</h1>
  <hr>
  <%= form_tag({controller: 'articles', action: 'index'}, method: 'get') do %>
    <div class="form-group row">
      <label class="mr-10">プログラミング言語:</label>
      <%= collection_select :article, :language_id, @languages, :id, :name, { include_blank: true }, class:'form-control col-md-6 mr-10' %>
      <%= submit_tag '検索', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>プログラミング言語</th>
      <th>セクションタイトル</th>
      <th>記事タイトル</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.language.name %></td>
        <td><%= article.section.title %></td>
        <td><%= article.title %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: '削除してよろしいでしょうか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to '新しい記事を追加', new_article_path %>
</div>
<div>
  <%= link_to 'ポータル画面に戻る', portal_articles_path %>
</div>

app/views/articles/new.html.erb
<script type="text/javascript">
  $(function(){
    $("#language_id").change(function(){
      language_id = $("#language_id").val();
      if (language_id != "") {
        location.href = "<%= url_for controller: 'articles', action: 'new', only_path: false %>?language_id=" + language_id;
      } else {
        location.href = "<%= url_for controller: 'articles', action: 'new', only_path: false %>"
      }
    });
  });
</script>
<h1>記事を追加</h1>
<hr>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/portal.html.erb
<%= render 'partial/messages' %>
<h1>管理画面</h1>
<hr>
<div>
  <%= link_to '>> プログラミング言語を追加', languages_path %>
</div>
<div>
  <%= link_to '>> セクションタイトルを追加', sections_path %>
</div>
<div>
  <%= link_to '>> 記事を追加', articles_path %>
</div>
<div>
  <%= link_to '>> お問い合わせ確認', infomations_path %>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3>プログラミング言語: <%= @article.language.name %></h3>
</p>

<p>
  <h3>セクションタイトル: <%= @article.section.title %></h3>
</p>

<script type="text/javascript">
  $('body').scrollspy({ target: '#navbar-scrollspy' });
  $('[data-spy="scroll"]').each(function () {
    var $spy = $(this).scrollspy('refresh');
  });
</script>

<h1><%= @article.title %></h1>
<hr>
<div class="row">
  <div data-spy="scroll" data-target="#navbar-scrollspy" data-offset="0" class="scrollspy col-md-9">
    <%= markdown(@article.body).html_safe %>
  </div>


  <div class="col-md-3">
    <nav id="navbar-scrollspy" class="style-scrollspy mb-30">
      <nav class="nav nav-pills flex-column">
        <h5 class="text-center">目次</h5>
        <% @items.each do |key, value| %>
          <a class="nav-link" href="#<%= key %>"><%= value %></a>
        <% end %>
      </nav>
    </nav>
    <div class="list-group">
      <% @articles = Article.limit(5).order(updated_at: :desc) %>
      <span class="list-group-item text-center">最新記事</span>
      <% @articles.each do |article| %>
        <%= link_to article.title, issue_path(article), class: "list-group-item" %>
      <% end %>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>