config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    collection do
      get :portal
    end
  end
  resources :languages
  resources :sections
  resources :issues, only: [:index, :show] do
    collection do
      get :portal
    end
  end
  resources :infomations, except: [:edit] do
    collection do
      get :complete
    end
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'issues#portal'
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :articles
  has_many :sections

  validates :name,
    presence: true
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user

  def index
    @languages = Language.all
  end

  def show
  end

  def new
    @language = Language.new
  end

  def edit
  end

  def create
    @language = Language.new(language_params)
    if @language.save
      redirect_to @language, notice: 'プログラミング言語が作成されました'
    else
      render :new
    end
  end

  def update
    if @language.update(language_params)
      redirect_to @language, notice: 'プログラミング言語が更新されました'
    else
      render :edit
    end
  end

  def destroy
    @language.destroy
    redirect_to languages_url, notice: 'プログラミング言語が削除されました'
  end

  private
    def set_language
      @language = Language.find(params[:id])
    end

    def language_params
      params.require(:language).permit(:name)
    end
end

app/views/languages/_form.html.erb
<%= form_with(model: language, local: true) do |form| %>
  <% if language.errors.any? %>
    <%= render 'partial/errors', error_model: language %>
  <% end %>


  <table id="form_table">
    <tr>
      <td>
        <%= form.label :name %>:
      </td>
      <td>
        <%= form.text_field :name, id: :language_name, class:"form-control col-md-8 ml-10" %>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>プログラミング言語を編集</h1>
<hr>

<%= render 'form', language: @language %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>プログラミング言語一覧</h1>
<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>プログラミング言語</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.id %></td>
        <td><%= language.name %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: '削除してよろしいでしょうか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div>
  <%= link_to 'プログラミング言語の追加', new_language_path %>
</div>
<div>
  <%= link_to 'ポータル画面に戻る', portal_articles_path %>
</div>

app/views/languages/new.html.erb
<h1>プログラミング言語を追加</h1>
<hr>

<%= render 'form', language: @language %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>

<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>