config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    collection do
      get :portal
    end
  end
  resources :languages
  resources :sections
  resources :issues, only: [:index, :show] do
    collection do
      get :portal
    end
  end
  resources :infomations, except: [:edit] do
    collection do
      get :complete
    end
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'issues#portal'
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :language, optional: true
  has_many :articles

  validates :language_id,
    presence: true

  validates :title,
    presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :set_language, only: [:new, :edit, :create, :update]
  before_action :authenticate_user

  def index
    @sections = Section.all
  end

  def show
  end

  def new
    @section = Section.new
  end

  def edit
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to @section, notice: 'セクションが作成されました'
    else
      render :new
    end
  end

  def update
    if @section.update(section_params)
      redirect_to @section, notice: 'セクションが更新されました'
    else
      render :edit
    end
  end

  def destroy
    @section.destroy
    redirect_to sections_url, notice: 'セクションが削除されました'
  end

  private
    def set_section
      @section = Section.find(params[:id])
    end

    def set_language
      @languages = Language.all
    end

    def section_params
      params.require(:section).permit(:language_id, :title)
    end
end

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <%= render 'partial/errors', error_model: section %>
  <% end %>

  <table id="form_table">
    <tr>
      <td>
        <%= form.label :language_id %>:
      </td>
      <td>
        <%= form.collection_select :language_id, @languages, :id, :name, { include_blank: true }, class:"form-control col-md-8 ml-10" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :title %>:
      </td>
      <td>
        <%= form.text_area :title, id: :section_title, class:"form-control col-md-8 ml-10", rows: 5 %>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>セクションタイトルを編集</h1>
<hr>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>セクションタイトル一覧</h1>
<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>プログラミング言語</th>
      <th>記事タイトル</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.id %></td>
        <td><%= section.language.name %></td>
        <td><%= section.title %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: '削除してよろしいでしょうか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= link_to '新しいセクションタイトルを追加', new_section_path %>
</div>
<div>
  <%= link_to 'ポータル画面に戻る', portal_articles_path %>
</div>

app/views/sections/new.html.erb
<h1>セクションタイトルを追加</h1>
<hr>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @section.language.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>