config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    collection do
      get :portal
    end
  end
  resources :languages
  resources :sections
  resources :issues, only: [:index, :show] do
    collection do
      get :portal
    end
  end
  resources :infomations, except: [:edit] do
    collection do
      get :complete
    end
  end
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'issues#portal'
end

app/views/partial/_errors.html.erb
<div id="error_explanation">
  <h2>以下のエラーを解消してください</h2>
  <ul>
  <% error_model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>

app/views/partial/_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <div><%= msg %></div>
  </div>
<% end %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'rubier', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% languages = Language.all %>
      <% if languages.present? %>
        <% languages.each do |language| %>
          <li class="nav-item">
            <%= link_to language.name, issues_path(language_id: language.id), class: 'nav-link' %>
          </li>
        <% end %>
      <% end %>
      <!-- <li class="nav-item">
        <a class="nav-link" href="#">広告について</a>
      </li> -->
      <li class="nav-item">
        <%= link_to "お問い合わせ", new_infomation_path, class: 'nav-link' %>
      </li>
      <% if logged_in? %>
        <%= link_to "管理画面へ", portal_articles_path, class: 'nav-link' %>
      <% end %>
    </ul>
    <ul class="navbar-nav navbar-right">
      <li class="nav-item">
        <% if logged_in? %>
          <%= link_to "ログアウト", logout_path, method: 'delete', class: 'nav-link' %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>